---
resources:
- name: spec_extractor
  type: git
  source:
    uri: https://github.com/sks/spec_extractor
    branch: develop
- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release
    branch: master

jobs:
- name: extract-cf-release-specs
  plan:
  - aggregate:
    - get: spec_extractor
    - get: bosh_release
      trigger: true
      resource: cf-release
  - task: extract_specs
    file: spec_extractor/ci/task/extract_specs/task.yml
